from typing import Dict, List, Callable

current_sys_cmds: Dict[str, List[str]] = {'Windows': ['dir', 'type', 'rmdir', 'copy', 'move', 'tasklist', 'taskkill', 'ipconfig', 'ping', 'del', 'md', 'help', 'cls', 'cd', 'pip', 'python', 'ren', 'xcopy', 'robocopy', 'sfc', 'chkdsk', 'diskpart', 'systeminfo', 'netstat', 'tracert', 'powercfg'], 'Linux/macOS': ['ls', 'cat', 'rm', 'mkdir', 'pwd', 'cp', 'mv', 'touch', 'ln', 'rmdir', 'grep', 'find', 'sort', 'uniq', 'wc', 'cut', 'awk', 'sed', 'head', 'tail', 'less', 'more', 'diff', 'cmp', 'patch', 'ps', 'top', 'htop', 'iotop', 'nmon', 'sar', 'vmstat', 'iostat', 'uptime', 'free', 'df', 'du', 'lsof', 'fuser', 'stat', 'chmod', 'chown', 'chgrp', 'passwd', 'chpasswd', 'useradd', 'usermod', 'userdel', 'groupadd', 'groupdel', 'groupmod', 'id', 'groups', 'who', 'w', 'last', 'lastlog', 'faillog', 'ping', 'ip', 'ifconfig', 'netstat', 'ss', 'route', 'traceroute', 'curl', 'wget', 'wget2', 'scp', 'sftp', 'ssh', 'ssh-keygen', 'ssh-copy-id', 'nc', 'telnet', 'dig', 'nslookup', 'host', 'apt', 'apt-get', 'apt-cache', 'yum', 'dnf', 'brew', 'dpkg', 'rpm', 'dpkg-query', 'tar', 'gzip', 'bzip2', 'xz', 'unzip', 'rsync', 'sudo', 'su', 'visudo', 'sudoedit', 'systemctl', 'service', 'journalctl', 'dmesg', 'cron', 'crontab', 'at', 'batch', 'iptables', 'ufw', 'firewalld-cmd', 'openssl', 'base64', 'mount', 'umount', 'fdisk', 'parted', 'lsblk', 'blkid', 'findmnt', 'duf', 'kill', 'killall', 'pkill', 'renice', 'nice', 'which', 'whereis', 'file', 'md5sum', 'sha256sum', 'openssl', 'nc', 'nmap', 'arp-scan', 'tcpdump', 'tshark', 'python', 'pip', 'gcc', 'clang', 'nano', 'uname', 'hostname', 'hostnamectl', 'timedatectl', 'systeminfo', 'echo', 'help', 'clear', 'history', 'date', 'expr', 'bc', 'dc', 'seq', 'printf', 'yes', 'false', 'true', 'sleep', 'usleep', 'timeout', 'nohup', 'setsid', 'screen', 'tmux', 'logout', 'shutdown', 'reboot', 'halt', 'poweroff'], 'Termux': ['ls', 'cat', 'rm', 'mkdir', 'pwd', 'cp', 'mv', 'touch', 'rmdir', 'grep', 'find', 'sort', 'uniq', 'wc', 'cut', 'awk', 'sed', 'head', 'tail', 'ps', 'top', 'free', 'df', 'du', 'uptime', 'chmod', 'chown', 'su', 'pkg', 'pkg search', 'pkg install', 'pkg remove', 'pkg upgrade', 'ping', 'curl', 'wget', 'scp', 'ssh', 'tar', 'unzip', 'python', 'pip', 'nano', 'gcc', 'clang', 'termux-setup-storage', 'termux-open', 'uname', 'hostname', 'echo', 'help', 'clear', 'history', 'date', 'sleep', 'nmap', 'node', 'stress-ng'], 'SpecialLinux': ['ls', 'cat', 'rm', 'mkdir', 'pwd', 'cp', 'mv', 'touch', 'grep', 'find', 'sort', 'uniq', 'wc', 'cut', 'awk', 'sed', 'ps', 'top', 'free', 'df', 'du', 'lsof', 'uptime', 'chmod', 'chown', 'sudo', 'ping', 'ip', 'netstat', 'ss', 'curl', 'wget', 'scp', 'ssh', 'nc', 'netcat', 'tcpdump', 'tshark', 'traceroute', 'nmap', 'msfconsole', 'hydra', 'sqlmap', 'arp-scan', 'hashcat', 'john', 'burpsuite', 'zaproxy', 'aircrack-ng', 'nikto', 'gobuster', 'ffuf', 'wpscan', 'xsser', 'sqlninja', 'hashid', 'exiftool', 'steghide', 'apt', 'apt-get', 'python', 'pip', 'nano', 'openssl', 'echo', 'help', 'clear', 'history', 'date', 'sleep']}

WIN_CMD_MAP: Dict[str, str] = {}
SPECIAL_CMD_MAP: Dict[str, str] = {}
SYS_SPECIFIC: Dict[str, any] = {'preinstall_tools': {'port_tool': '/usr/bin/nmap', 'exploit_tool': '/usr/bin/msfconsole', 'crack_tool': '/usr/bin/hydra', 'arp_tool': '/usr/bin/arp-scan', 'sql_tool': '/usr/bin/sqlmap', 'web_tool': '/usr/bin/zaproxy', 'wireless_tool': '/usr/bin/aircrack-ng', 'hash_tool': '/usr/bin/hashcat', 'john_tool': '/usr/bin/john', 'burp_tool': '/usr/bin/burpsuite'}, 'quick_alias': {'port': 'nmap', 'exploit': 'msfconsole', 'crack': 'hydra', 'arp': 'arp-scan', 'sql': 'sqlmap', 'web': 'zaproxy', 'wireless': 'aircrack-ng', 'hash': 'hashcat', 'john': 'john', 'burp': 'burpsuite'}, 'repo_update_cmd': 'sudo apt update && sudo apt upgrade -y', 'tool_config_rule': {'config_file': 'config.conf', 'fields': {'author': 'author = ', 'name': 'name = ', 'version': 'version = ', 'cli': 'cli = ', 'type': 'type = ', 'introduction': 'introduction = '}}, 'perm_file': '.perm'}

BUILTIN_COMMANDS: Dict[str, Callable[[List[str], str], None]] = {}
